;; m-x list-colors-display, list-faces-display
;; c-u c-x =
;; emacs colors: http://raebear.net/comp/emacscolors.html
(defun color-theme-winfred ()
  (interactive)
  (color-theme-install
   '(color-theme-winfred
     ((background-color . "black")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "black")
      (foreground-color . "gray")
      (mouse-color . "black"))
     ((blank-space-face . blank-space-face)
      (blank-tab-face . blank-tab-face)
      (list-matching-lines-face . bold)
      (Man-reverse-face . highlight)
      (Man-overstrike-face . ((t (:bold t :foreground "#d0a0c0"))))
      (Man-underline-face . ((t (:underline t :foreground "#a0d0d0"))))
      (view-highlight-face . highlight))
     (default ((t (nil))))
     (blank-space-face ((t (:background "LightGray"))))
     (blank-tab-face ((t (:background "green" :foreground "black"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:italic t :bold t))))
     (minibuffer-prompt ((t (:foreground "dark sea green"))))

     (buffer-menu-star-buffer ((t (:foreground "#d0d050"))))
     (buffer-menu-directory-buffer ((t (:background "#402010" :foreground "#d0d020"))))
     (buffer-menu-modified-mark ((t (:foreground "#50d0d0"))))
     (buffer-menu-read-only-mark ((t (:foreground "#2020d0"))))
     (buffer-menu-buffer-name ((t (:foreground "#d0d020"))))
     (buffer-menu-mode ((t (:foreground "#d070d0"))))
     (buffer-menu-size ((t (:foreground "#50d0d0"))))
     (buffer-menu-time ((t (:foreground "#5070d0"))))
     (buffer-menu-file-name ((t (:foreground "#50d050"))))

     (compilation-info ((t (:foreground "#2a552a"))))

     (cscope-file-face ((t (:foreground "#808030"))))
     (cscope-function-face ((t (:foreground "#208080"))))
     (cscope-line-face ((t (:foreground "#208020"))))
     (cscope-line-number-face ((t (:foreground "#802020"))))

     (diff-refine-change ((t (nil))))

     (ediff-current-diff-A ((t (:foreground "black" :background "#a07070"))))
     (ediff-current-diff-B ((t (:foreground "black" :background "#70a070"))))
     (ediff-even-diff-A ((t (:background "#111111"))))
     (ediff-even-diff-B ((t (:background "#222222"))))
     (ediff-fine-diff-A ((t (:foreground "#440000" :background "#eec0c0"))))
     (ediff-fine-diff-B ((t (:foreground "#001100" :background "#d0ffd0"))))
     (ediff-odd-diff-A ((t (:background "#222222"))))
     (ediff-odd-diff-B ((t (:background "#111111"))))

     (egg-section-title ((t (:foreground "#70b0a0"))))
     (egg-branch ((t (:bold t :foreground "#e0e050"))))
     (egg-term ((t (:foreground "#d0d040"))))
     (egg-diff-add ((t (:foreground "PaleGreen3"))))
     (egg-diff-del ((t (:foreground "salmon"))))

     (font-lock-constant-face ((t (:foreground "#c0a070"))))
     (font-lock-comment-face ((t (:italic t :foreground "#707070"))))
     (font-lock-keyword-face ((t (:foreground "#90b0e0"))))
     (font-lock-preprocessor-face ((t (:italic t :foreground "#5070b0"))))
     (font-lock-string-face ((t (:foreground "#b0b070"))))
     (font-lock-variable-name-face ((t (:foreground "#6070d0"))))
     (font-lock-function-name-face ((t (:italic t :foreground "#b06090"))))
     (font-lock-type-face ((t (:foreground "#60b070"))))
     (font-lock-warning-face ((t (:bold t :foreground "#e05050"))))

     (highlight ((t (:background "dark slate blue" :foreground "#90a0f0"))))
     (ido-first-match ((t (:bold t :foreground "antique white"))))
     (ido-only-match ((t (:foreground "dark sea green"))))
     (ido-subdir ((t (:foreground "rosy brown"))))
     (isearch ((t (:background "#a05050" :foreground "#50a0a0"))))
     (ispell-face ((t (:bold t :background "#f0b070" :foreground "#90e080"))))
     (italic ((t (:italic t))))

     (link ((t (:underline t :foreground "#2a5580"))))
     (link-visited ((t (:underline t :foreground "#802a55"))))

     (magit-log-sha1 ((t (:foreground "#cf6a4c"))))
     (magit-log-head-label-local ((t (:foreground "#3387cc"))))
     (magit-log-head-label-remote ((t (:foreground "#65b042"))))
     (magit-branch ((t (:foreground "#e9c062"))))
     (magit-section-title ((t (:foreground "#9b859d"))))
     (magit-item-highlight ((t (:background "#1f1f1f"))))
     (magit-diff-add ((t (:foreground "PaleGreen3"))))
     (magit-diff-del ((t (:foreground "salmon"))))

     (match ((t (:background "#b0b050" :foreground "#101010"))))
     (menu ((t (:background "#304020" :foreground "navajo white"))))
     (modeline ((t (:background "#302060" :foreground "#c0c0d0"))))
     (modeline-mousable ((t (:background "light goldenrod" :foreground "dim gray"))))
     (modeline-mousable-minor-mode ((t (:background "dim gray" :foreground "light goldenrod"))))

     (org-date ((t (:underline t :foreground "#80a0b0"))))
     (org-hide ((t (:foreground "black"))))
     (org-level-1 ((t (:foreground "#e09090"))))
     (org-level-2 ((t (:foreground "#e0a080"))))
     (org-level-3 ((t (:foreground "#e0e090"))))
     (org-level-4 ((t (:foreground "#a0e090"))))
     (org-level-5 ((t (:foreground "#a0c0e0"))))
     (org-level-6 ((t (:foreground "#a0a0e0"))))
     (org-level-7 ((t (:foreground "#e0a0d0"))))
     (org-level-8 ((t (:foreground "#808080"))))
     (org-table ((t (:foreground "#9fc59f"))))
     (org-link ((t (:underline t :foreground "#00a0a0"))))

     (region ((t (:background "dark slate gray"))))
     (secondary-selection ((t (:background "dark slate blue" :foreground "light goldenrod"))))
     (show-paren-match-face ((t (:background "turquoise" :foreground "black"))))
     (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
     (underline ((t (:underline t))))
     (zmacs-region ((t (:background "dark slate gray")))))))

