;; m-x list-colors-display, list-faces-display
;; c-u c-x =
;; emacs colors: http://raebear.net/comp/emacscolors.html
(defun color-theme-winfred ()
  (interactive)
  (color-theme-install
   '(color-theme-winfred
     (;(background-color . "black")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "black")
      (foreground-color . "gray")
      (mouse-color . "black"))
     ((blank-space-face . blank-space-face)
      (blank-tab-face . blank-tab-face)
      (list-matching-lines-face . bold)
      (Man-reverse-face . highlight)
      (Man-overstrike-face . ((t (:bold t :foreground "#d0a0c0"))))
      (Man-underline-face . ((t (:underline t :foreground "#a0d0d0"))))
      (view-highlight-face . highlight))
     (default ((t (nil))))
     (blank-space-face ((t (:background "LightGray"))))
     (blank-tab-face ((t (:background "green" :foreground "black"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:italic t :bold t))))
     (minibuffer-prompt ((t (:foreground "dark sea green"))))

     (buffer-menu-star-buffer ((t (:foreground "#d0d050"))))
     (buffer-menu-directory-buffer ((t (:background "#402010" :foreground "#d0d020"))))
     (buffer-menu-modified-mark ((t (:foreground "#50d0d0"))))
     (buffer-menu-read-only-mark ((t (:foreground "#2020d0"))))
     (buffer-menu-buffer-name ((t (:foreground "#d0d020"))))
     (buffer-menu-mode ((t (:foreground "#d070d0"))))
     (buffer-menu-size ((t (:foreground "#50d0d0"))))
     (buffer-menu-time ((t (:foreground "#5070d0"))))
     (buffer-menu-file-name ((t (:foreground "#50d050"))))

     (compilation-info ((t (:foreground "#2a552a"))))

     (cscope-file-face ((t (:foreground "#808030"))))
     (cscope-function-face ((t (:foreground "#208080"))))
     (cscope-line-face ((t (:foreground "#208020"))))
     (cscope-line-number-face ((t (:foreground "#802020"))))

     (diff-file-header ((t (:foreground "white" :bold t))))
     (diff-header ((t (:foreground "DodgerBlue4"))))
     (diff-added ((t (:foreground "SeaGreen"))))
     (diff-changed ((t (:foreground "RosyBrown"))))
     (diff-removed ((t (:foreground "IndianRed"))))
     (diff-refine-change ((t (nil))))

     (ediff-current-diff-A ((t (:foreground "black" :background "#a07070"))))
     (ediff-current-diff-B ((t (:foreground "black" :background "#70a070"))))
     (ediff-even-diff-A ((t (:background "#111111"))))
     (ediff-even-diff-B ((t (:background "#222222"))))
     (ediff-fine-diff-A ((t (:foreground "#440000" :background "#eec0c0"))))
     (ediff-fine-diff-B ((t (:foreground "#001100" :background "#d0ffd0"))))
     (ediff-odd-diff-A ((t (:background "#222222"))))
     (ediff-odd-diff-B ((t (:background "#111111"))))

     (egg-section-title ((t (:foreground "#70b0a0"))))
     (egg-branch ((t (:bold t :foreground "#e0e050"))))
     (egg-term ((t (:foreground "#d0d040"))))
     (egg-diff-add ((t (:foreground "PaleGreen3"))))
     (egg-diff-del ((t (:foreground "salmon"))))

     (font-lock-constant-face ((t (:foreground "#c0a070"))))
     (font-lock-comment-face ((t (:foreground "#707070"))))
     (font-lock-keyword-face ((t (:foreground "#90b0e0"))))
     (font-lock-preprocessor-face ((t (:foreground "#5070b0"))))
     (font-lock-string-face ((t (:foreground "#b0b070"))))
     (font-lock-variable-name-face ((t (:foreground "#6070d0"))))
     (font-lock-function-name-face ((t (:foreground "#b06090"))))
     (font-lock-type-face ((t (:foreground "#60b070"))))
     (font-lock-warning-face ((t (:bold t :foreground "#e05050"))))

     (highlight ((t (:background "dark slate blue" :foreground "#90a0f0"))))
     (ido-first-match ((t (:bold t :foreground "antique white"))))
     (ido-only-match ((t (:foreground "dark sea green"))))
     (ido-subdir ((t (:foreground "rosy brown"))))
     (isearch ((t (:background "#a05050" :foreground "#50a0a0"))))
     (ispell-face ((t (:bold t :background "#f0b070" :foreground "#90e080"))))
     (italic ((t (:italic t))))

     (link ((t (:underline t :foreground "#2a5580"))))
     (link-visited ((t (:underline t :foreground "#802a55"))))

     (magit-log-sha1 ((t (:foreground "#cf6a4c"))))
     (magit-log-head-label-local ((t (:foreground "#3387cc"))))
     (magit-log-head-label-remote ((t (:foreground "#65b042"))))
     (magit-branch ((t (:foreground "#e9c062"))))
     (magit-section-title ((t (:foreground "#9b859d"))))
     (magit-item-highlight ((t (:background "#1f1f1f"))))
     (magit-diff-add ((t (:foreground "PaleGreen3"))))
     (magit-diff-del ((t (:foreground "salmon"))))

     (match ((t (:background "#b0b050" :foreground "#101010"))))
     (menu ((t (:background "#304020" :foreground "navajo white"))))
     (mode-line ((t (:background "MediumPurple4" :foreground "#c0c0d0"))))
     (mode-line-buffer-id ((t (:foreground "RosyBrown2"))))
     (mode-line-mousable ((t (:background "light goldenrod" :foreground "dim gray"))))
     (mode-line-mousable-minor-mode ((t (:background "dim gray" :foreground "light goldenrod"))))

     (org-date ((t (:underline t :foreground "#80a0b0"))))
     (org-hide ((t (:foreground "black"))))
     (org-level-1 ((t (:foreground "#e09090"))))
     (org-level-2 ((t (:foreground "#e0a080"))))
     (org-level-3 ((t (:foreground "#e0e090"))))
     (org-level-4 ((t (:foreground "#a0e090"))))
     (org-level-5 ((t (:foreground "#a0c0e0"))))
     (org-level-6 ((t (:foreground "#a0a0e0"))))
     (org-level-7 ((t (:foreground "#e0a0d0"))))
     (org-level-8 ((t (:foreground "#808080"))))
     (org-table ((t (:foreground "#9fc59f"))))
     (org-link ((t (:underline t :foreground "#00a0a0"))))

     (region ((t (:background "dark slate gray"))))
     (secondary-selection ((t (:background "dark slate blue" :foreground "light goldenrod"))))
     (show-paren-match-face ((t (:background "turquoise" :foreground "black"))))
     (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
     (underline ((t (:underline t))))
     (zmacs-region ((t (:background "dark slate gray")))))))


(defun color-theme-jsc-light ()
  "Color theme by John S Cooper, created 2000-06-08."
  (interactive)
  (color-theme-install
   '(color-theme-jsc-light
     ((background-color . "white")
      (background-mode . light)
      (border-color . "black")
      (cursor-color . "Red")
      (foreground-color . "black")
      (mouse-color . "black"))
     ((gnus-mouse-face . highlight)
      (list-matching-lines-face . bold)
      (view-highlight-face . highlight))
     (default ((t (nil))))
    (bold ((t (:bold t :foreground "red3"))))
    (bold-italic ((t (:italic t :bold t :foreground "red"))))
    (custom-button-face ((t (nil))))
    (custom-changed-face ((t (:background "blue" :foreground "white"))))
    (custom-documentation-face ((t (nil))))
    (custom-face-tag-face ((t (:underline t))))
    (custom-group-tag-face ((t (:underline t :foreground "blue"))))
    (custom-group-tag-face-1 ((t (:underline t :foreground "red"))))
    (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
    (custom-modified-face ((t (:background "blue" :foreground "white"))))
    (custom-rogue-face ((t (:background "black" :foreground "pink"))))
    (custom-saved-face ((t (:underline t))))
    (custom-set-face ((t (:background "white" :foreground "blue"))))
    (custom-state-face ((t (:foreground "dark green"))))
    (custom-variable-button-face ((t (:underline t :bold t))))
    (custom-variable-tag-face ((t (:underline t :foreground "blue"))))
    (font-lock-builtin-face ((t (:foreground "Orchid"))))
    (font-lock-comment-face ((t (:italic t :bold t :foreground "Red3"))))
    (font-lock-constant-face ((t (:foreground "navy"))))
    (font-lock-function-name-face ((t (:bold t :foreground "Blue"))))
    (font-lock-keyword-face ((t (:bold t :foreground "Purple"))))
    (font-lock-string-face ((t (:foreground "Green4"))))
    (font-lock-type-face ((t (:foreground "Navy"))))
    (font-lock-variable-name-face ((t (:foreground "Tan4"))))
    (font-lock-warning-face ((t (:bold t :foreground "Red"))))
    (gnus-cite-attribution-face ((t (:italic t))))
    (gnus-cite-face-1 ((t (:foreground "MidnightBlue"))))
    (gnus-cite-face-10 ((t (:foreground "medium purple"))))
    (gnus-cite-face-11 ((t (:foreground "turquoise"))))
    (gnus-cite-face-2 ((t (:foreground "firebrick"))))
    (gnus-cite-face-3 ((t (:foreground "dark green"))))
    (gnus-cite-face-4 ((t (:foreground "OrangeRed"))))
    (gnus-cite-face-5 ((t (:foreground "dark khaki"))))
    (gnus-cite-face-6 ((t (:foreground "dark violet"))))
    (gnus-cite-face-7 ((t (:foreground "SteelBlue4"))))
    (gnus-cite-face-8 ((t (:foreground "magenta"))))
    (gnus-cite-face-9 ((t (:foreground "violet"))))
    (gnus-emphasis-bold ((t (:bold t))))
    (gnus-emphasis-bold-italic ((t (:italic t :bold t))))
    (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
    (gnus-emphasis-italic ((t (:italic t))))
    (gnus-emphasis-underline ((t (:underline t))))
    (gnus-emphasis-underline-bold ((t (:underline t :bold t))))
    (gnus-emphasis-underline-bold-italic ((t (:underline t :italic t :bold t))))
    (gnus-emphasis-underline-italic ((t (:underline t :italic t))))
    (gnus-group-mail-1-empty-face ((t (:foreground "DeepPink3"))))
    (gnus-group-mail-1-face ((t (:bold t :foreground "DeepPink3"))))
    (gnus-group-mail-2-empty-face ((t (:foreground "HotPink3"))))
    (gnus-group-mail-2-face ((t (:bold t :foreground "HotPink3"))))
    (gnus-group-mail-3-empty-face ((t (:foreground "magenta4"))))
    (gnus-group-mail-3-face ((t (:bold t :foreground "magenta4"))))
    (gnus-group-mail-low-empty-face ((t (:foreground "DeepPink4"))))
    (gnus-group-mail-low-face ((t (:bold t :foreground "DeepPink4"))))
    (gnus-group-news-1-empty-face ((t (:foreground "blue2"))))
    (gnus-group-news-1-face ((t (:bold t :foreground "blue2"))))
    (gnus-group-news-2-empty-face ((t (:foreground "CadetBlue4"))))
    (gnus-group-news-2-face ((t (:bold t :foreground "CadetBlue4"))))
    (gnus-group-news-3-empty-face ((t (nil))))
    (gnus-group-news-3-face ((t (:bold t))))
    (gnus-group-news-4-empty-face ((t (nil))))
    (gnus-group-news-4-face ((t (:bold t))))
    (gnus-group-news-5-empty-face ((t (nil))))
    (gnus-group-news-5-face ((t (:bold t))))
    (gnus-group-news-6-empty-face ((t (nil))))
    (gnus-group-news-6-face ((t (:bold t))))
    (gnus-group-news-low-empty-face ((t (:foreground "DarkGreen"))))
    (gnus-group-news-low-face ((t (:bold t :foreground "DarkGreen"))))
    (gnus-header-content-face ((t (:italic t :foreground "blue"))))
    (gnus-header-from-face ((t (:foreground "red3"))))
    (gnus-header-name-face ((t (:foreground "red3"))))
    (gnus-header-newsgroups-face ((t (:italic t :foreground "MidnightBlue"))))
    (gnus-header-subject-face ((t (:bold t :foreground "red"))))
    (gnus-signature-face ((t (:foreground "pink"))))
    (gnus-splash-face ((t (:foreground "Brown"))))
    (gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))))
    (gnus-summary-high-ancient-face ((t (:bold t :foreground "RoyalBlue"))))
    (gnus-summary-high-read-face ((t (:bold t :foreground "navy"))))
    (gnus-summary-high-ticked-face ((t (:bold t :foreground "firebrick"))))
    (gnus-summary-high-unread-face ((t (:bold t :foreground "blue"))))
    (gnus-summary-low-ancient-face ((t (:italic t :foreground "RoyalBlue"))))
    (gnus-summary-low-read-face ((t (:italic t :foreground "DarkGreen"))))
    (gnus-summary-low-ticked-face ((t (:italic t :foreground "firebrick"))))
    (gnus-summary-low-unread-face ((t (:italic t))))
    (gnus-summary-normal-ancient-face ((t (:foreground "RoyalBlue"))))
    (gnus-summary-normal-read-face ((t (:foreground "red3"))))
    (gnus-summary-normal-ticked-face ((t (:foreground "black"))))
    (gnus-summary-normal-unread-face ((t (:bold t :foreground "red3"))))
    (gnus-summary-selected-face ((t (:underline t))))
    (highlight ((t (:background "antiquewhite" :foreground "blue"))))
    (italic ((t (:italic t))))
    (makefile-space-face ((t (:background "hotpink"))))
    (message-cited-text-face ((t (:foreground "red"))))
    (message-header-cc-face ((t (:foreground "MidnightBlue"))))
    (message-header-name-face ((t (:foreground "cornflower blue"))))
    (message-header-newsgroups-face ((t (:italic t :bold t :foreground "blue4"))))
    (message-header-other-face ((t (:foreground "steel blue"))))
    (message-header-subject-face ((t (:bold t :foreground "navy blue"))))
    (message-header-to-face ((t (:bold t :foreground "MidnightBlue"))))
    (message-header-xheader-face ((t (:foreground "blue"))))
    (message-mml-face ((t (:foreground "ForestGreen"))))
    (message-separator-face ((t (:foreground "brown"))))
    (mode-line ((t (:background "plum" :foreground "black"))))
    (mode-line-buffer-id ((t (:background "plum" :foreground "black"))))
    (mode-line-mousable ((t (:background "plum" :foreground "black"))))
    (mode-line-mousable-minor-mode ((t (:background "plum" :foreground "black"))))
    (region ((t (:background "plum"))))
    (secondary-selection ((t (:background "palegreen"))))
    (show-paren-match-face ((t (:background "plum"))))
    (show-paren-mismatch-face ((t (:background "navy" :foreground "white"))))
    (speedbar-button-face ((t (:foreground "green4"))))
    (speedbar-directory-face ((t (:foreground "blue4"))))
    (speedbar-file-face ((t (:foreground "cyan4"))))
    (speedbar-highlight-face ((t (:background "green"))))
    (speedbar-selected-face ((t (:underline t :foreground "red"))))
    (speedbar-tag-face ((t (:foreground "brown"))))
    (underline ((t (:underline t))))
    (widget-button-face ((t (:bold t))))
    (widget-button-pressed-face ((t (:foreground "red"))))
    (widget-documentation-face ((t (:foreground "dark green"))))
    (widget-field-face ((t (:background "gray85"))))
    (widget-inactive-face ((t (:foreground "dim gray"))))
    (widget-single-line-field-face ((t (:background "gray85")))))))


(defvar kconfig-mode-font-lock-keywords
  '(("^[\t, ]*\\_<bool\\_>" . font-lock-type-face)
    ("^[\t, ]*\\_<int\\_>" . font-lock-type-face)
    ("^[\t, ]*\\_<boolean\\_>" . font-lock-type-face)
    ("^[\t, ]*\\_<tristate\\_>" . font-lock-type-face)
    ("^[\t, ]*\\_<depends on\\_>" . font-lock-variable-name-face)
    ("^[\t, ]*\\_<select\\_>" . font-lock-variable-name-face)
    ("^[\t, ]*\\_<help\\_>" . font-lock-variable-name-face)
    ("^[\t, ]*\\_<---help---\\_>" . font-lock-variable-name-face)
    ("^[\t, ]*\\_<default\\_>" . font-lock-variable-name-face)
    ("^[\t, ]*\\_<range\\_>" . font-lock-variable-name-face)
    ("^\\_<config\\_>" . font-lock-constant-face)
    ("^\\_<comment\\_>" . font-lock-constant-face)
    ("^\\_<menu\\_>" . font-lock-constant-face)
    ("^\\_<endmenu\\_>" . font-lock-constant-face)
    ("^\\_<if\\_>" . font-lock-constant-face)
    ("^\\_<endif\\_>" . font-lock-constant-face)
    ("^\\_<menuconfig\\_>" . font-lock-constant-face)
    ("^\\_<source\\_>" . font-lock-keyword-face)
    ("\#.*" . font-lock-comment-face)
    ("\".*\"$" . font-lock-string-face)))

(define-derived-mode kconfig-mode text-mode
  "kconfig"
  (set (make-local-variable 'font-lock-defaults)
       '(kconfig-mode-font-lock-keywords t)))

(add-to-list 'auto-mode-alist '("Kconfig\\'" . kconfig-mode))
(add-to-list 'auto-mode-alist '("kcnf\\'" . kconfig-mode))
(add-to-list 'auto-mode-alist '("Config.in\\'" . kconfig-mode))
